-- 创建数据库和用户
CREATE DATABASE lifee;
CREATE USER lifee WITH ENCRYPTED PASSWORD 'lifee123';
GRANT ALL PRIVILEGES ON DATABASE lifee TO lifee;

-- 连接到lifee数据库
\c lifee;

-- 启用pgvector扩展
CREATE EXTENSION IF NOT EXISTS vector;

-- 授予用户权限
GRANT ALL ON SCHEMA public TO lifee;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO lifee;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO lifee;
GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA public TO lifee;

-- 设置默认权限
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO lifee;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO lifee;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON FUNCTIONS TO lifee;